name: rest_api_client
description: Abstraction for communicating with REST API in flutter projects. Incorporates exception handling and jwt with refresh token authorization.
version: 2.4.0
repository: https://github.com/salihagic/rest_api_client

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  storage_repository: ^2.0.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
