name: rest_api_client
description: Abstraction for communicating with REST API in flutter projects. Incorporates exception handling and jwt with refresh token authorization.
version: 1.1.12
repository: https://github.com/salihagic/rest_api_client

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.2.0
  crypto: ^3.0.1
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  storage_repository: ^1.1.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
